"""
validate_random.py

Cross-validates net_random.NetRandom against a trace captured from the real
.NET BCL's System.Random (seeded ctor), generated by a small C# console app
(see the "RandomOracle" scratchpad project referenced in
re_random_validation.md).

Usage:
    python validate_random.py <path-to-oracle_output.txt>

If no path is given, defaults to ORACLE_PATH below.

The oracle file format (produced by Program.cs) is a sequence of blocks:

    <LABEL>
    seed=<seed0>
    <value>            x20
    seed=<seed1>
    <value>            x20
    ...
    <NEXT LABEL>
    ...

Labels used:
    NEXT
    NEXT_MAX_10, NEXT_MAX_3, NEXT_MAX_1, NEXT_MAX_54
    NEXTDOUBLE                (values are C#'s ToString("R"))
    NEXT_RANGE_-5_5
    NEXT_RANGE_0_1000000

For every value, a FRESH Random(seed) [C# side] / NetRandom(seed) [Python
side] was used per block, so streams are directly comparable index-by-index.
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from net_random import NetRandom

COUNT = 20

DEFAULT_ORACLE_PATH = (
    r"C:\Users\ir0n1c\AppData\Local\Temp\claude\C--Users-ir0n1c-grannyseedpredictor"
    r"\cb0b7714-559d-4a3a-be99-f24a34d3393e\scratchpad\RandomOracle\oracle_output.txt"
)


def parse_oracle(path):
    """
    Returns a dict: { label: { seed: [values as strings] } }
    """
    blocks = {}
    current_label = None
    current_seed = None
    with open(path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.rstrip("\r\n")
            if not line:
                continue
            if line.startswith("seed="):
                current_seed = int(line[len("seed="):])
                blocks[current_label][current_seed] = []
            elif line.startswith(("NEXT", "NEXTDOUBLE")):
                # label line (NEXT, NEXT_MAX_10, NEXTDOUBLE, NEXT_RANGE_...)
                current_label = line
                blocks[current_label] = {}
                current_seed = None
            else:
                blocks[current_label][current_seed].append(line)
    return blocks


def compare_exact(label, seed, index, expected_str, actual, is_double=False):
    if is_double:
        expected = float(expected_str)
        actual_f = float(actual)
        # Bit-exact comparison via exact float equality (both IEEE-754
        # doubles); no tolerance is used since both sides are performing
        # the identical double-precision computation.
        return expected == actual_f, expected, actual_f
    else:
        expected = int(expected_str)
        return expected == actual, expected, actual


def main():
    oracle_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ORACLE_PATH
    if not os.path.isfile(oracle_path):
        print(f"ERROR: oracle file not found: {oracle_path}")
        sys.exit(2)

    blocks = parse_oracle(oracle_path)

    mismatches = []
    total_compared = 0

    def check_int_block(label, method):
        nonlocal total_compared
        if label not in blocks:
            print(f"WARNING: label '{label}' missing from oracle output; skipping")
            return
        for seed, values in blocks[label].items():
            rnd = NetRandom(seed)
            for i, expected_str in enumerate(values):
                actual = method(rnd)
                ok, expected, actual_v = compare_exact(label, seed, i, expected_str, actual)
                total_compared += 1
                if not ok:
                    mismatches.append((label, seed, i, expected, actual_v))

    def check_double_block(label, method):
        nonlocal total_compared
        if label not in blocks:
            print(f"WARNING: label '{label}' missing from oracle output; skipping")
            return
        for seed, values in blocks[label].items():
            rnd = NetRandom(seed)
            for i, expected_str in enumerate(values):
                actual = method(rnd)
                ok, expected, actual_v = compare_exact(
                    label, seed, i, expected_str, actual, is_double=True
                )
                total_compared += 1
                if not ok:
                    mismatches.append((label, seed, i, expected, actual_v))

    check_int_block("NEXT", lambda r: r.next())
    check_int_block("NEXT_MAX_10", lambda r: r.next_int(10))
    check_int_block("NEXT_MAX_3", lambda r: r.next_int(3))
    check_int_block("NEXT_MAX_1", lambda r: r.next_int(1))
    check_int_block("NEXT_MAX_54", lambda r: r.next_int(54))
    check_double_block("NEXTDOUBLE", lambda r: r.next_double())
    check_int_block("NEXT_RANGE_-5_5", lambda r: r.next_range(-5, 5))
    check_int_block("NEXT_RANGE_0_1000000", lambda r: r.next_range(0, 1000000))
    check_int_block(
        "NEXT_RANGE_MIN_MAX", lambda r: r.next_range(-2147483648, 2147483647)
    )

    print(f"Total values compared: {total_compared}")
    print(f"Mismatches: {len(mismatches)}")
    if mismatches:
        print("\nFirst mismatches:")
        for label, seed, i, expected, actual in mismatches[:50]:
            print(f"  [{label}] seed={seed} index={i} expected={expected!r} actual={actual!r}")
        print("\nRESULT: FAIL")
        sys.exit(1)
    else:
        print("\nRESULT: PASS")
        sys.exit(0)


if __name__ == "__main__":
    main()
